# General Jekyll Config
markdown: rdiscount
permalink: /posts/:title
timezone: America/Detroit
rdiscount:
  extensions: [smart]
pygments: true
url: http://chipkoziara.com
lsi: false
exclude: [DRAFTS, README.md]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#FF7D5A'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: chipkoziara
    twitter: chipkoziara
    hacker_news: fjk

  # "Hi, I'm Chip"
  name: Chip Koziara
  email: chip@chipkoziara.com
  tagline: "Eager to learn and do"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-43189255-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
